### ISSUE TITLE
Systems still missing

### ISSUE THREAD

**Issue by cosmo0** [chicueloarcade/es-theme-Chicuelo#26]
A small number of "main" systems are still missing something (character, logo, or controller).

- [x] sg-1000 - Sega SG-1000
Character: Flicky

- [x] ngp & ngpc - NeoGeo Pocket / Color
Character: chibi Kyo from King of Fighters

- [x] nds - Nintendo DS
Character: Either Professor Layton, or Phoenix Wright.

- [x] msx & msx2 - MSX (various)
Character: Solid Snake or Goemon

**Comment by Pit1209** [comment]
Also wii

**Comment by chicueloarcade** [comment]
Wii, WiiU, Sg1000, Ps2, ngp, ngpc, Nds added.

MSX and MSX2 with brand should I use?

**Comment by movisman** [comment]
Hey :)

Good question that! Just spotted your comment in my mail client, as I have the repo started. I never had an MSX, however looking at the Wikipedia page for it, it appears Panasonic were the only manufacturer to make a machine for all three generations - as they made the MSX TurboR after the MSX2/MSX2+ generation and no-one else did. So if you have to pick one....i'd probably go for Panasonic?

Someone may disagree but I think that would be a reasonable pick!

Cheers!

**Comment by chicueloarcade** [comment]
Great! Panasonic will be!

**Comment by chicueloarcade** [comment]
msx and msx2 added
